package interfaces;

/**
 * This is an abstract class based on specific language parser
 * which will provide language specific tokens and AST
 */
public abstract class PythonParser implements ParserVisitable{

    /**
     * This methods generates tokens based on specific language parser and
     * returns AST based on the tokens generated by parse
     * @return AST object representing AST of tokens
     */
    public abstract ASTClass accept();
}
